apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5yZWRoYXQuaW8iOiB7CiAgICAgICJhdXRoIjogImV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKbE1XWTROR05rTnpaaFpHWTBNVE5sT0Rkak16TTNZMlpqWldFMk56QTVOeUo5LnJtV0xMUU01dG1zbGctM0Ewb21BenczNWZ3bzZHMXJMSzFha2tTUlNZWWd4eTNucVNia3JSMUl5SDlhaGE2ZzYtV3VVS01HVUFnV0YweEFhZU5sQ053V2tEai1ZWWVHQXN2T3Jzd05SUDcyVDNPaWREa1JnNHIweXd4cEpmT3l0dWRCWE1DSGFPWXFSU3RCc291Z2JSeXdHVWw5TF9KSFAtMUZMOU9EaEFPeF9aclJ2N1p0TktjcmRaeFROZk1aZjFxU1Y1UW42OWU1eVBpOFYtTld3TE90cTNHdFpETEt5eWlZNy0wZ0JBUjhaWUxrR2VKOHJ3UjV5N3pfWjkwUEZTY1lfWEdFYThMSWRaWEdVTkVfbVF1bTJzSzRaUlROVjgtcy1lanl3MlFfYTgtXzhaYTFYUk9LRnU2dkJfMi1LbnFnd1pnQWtJYXljUUFlRFBIMktTM0g4REFXZE1FNjJmTFgzRDR6ZDlTQWZYQW9QZGRocFNiRDZ0eXdMOVREb3ZaamY4MU5CZ3ZsMUhCUVpHcG45d3BqblVDUk4zSWxFbWtSOThIOW40UFFzQWQzQ3RGbm1EXzdoQW1DSndGZHFXN3J4NjBoU0lXWWI5TXJ1ZXBJaTY2dFZmRHBzSE9pZFNFa2tvWUNiT0xnLWM3c3kyNTVZMzViQXh6aHpqenFDdmE5SmdER0plLUVJTlN4WHZ6Z04wbmRpUzZLM0pnc0pIcW5fUldyUmx5bkIyb25OaG5qSXBRejFZTzhvaElLYmowTFNHclhueDlJb0FOYkVaaXI3NFpuQV9tQm1DS2tWRUVJSlFTMGw4TnVVWk9VZDhPamhjQ1U2U18tMlVfUWpyWHExeXJocG1VdlFBdnpmcEt4SHlHaXNkTkE3MGoxelEwYWg1WF9lb3JvIgogICAgfQogIH0KfQ==
kind: Secret
metadata:
  annotations:
    appstudio.redhat.com/linked-remote-secrets: rhtas-tenant/db-image-pull-secret
    appstudio.redhat.com/managing-remote-secret: rhtas-tenant/db-image-pull-secret
  creationTimestamp: "2023-10-06T09:26:59Z"
  generateName: db-image-pull-secret-secret-
  labels:
    appstudio.redhat.com/linked-by-remote-secret: "true"
  name: db-image-pull-secret
  namespace: rhtas-tenant
  resourceVersion: "745445190"
  uid: 76458bc9-988c-4d0c-8ee4-817f075ea61f
type: kubernetes.io/dockerconfigjson
