# Provides the Trusted Artifact Signer CLI binaries, cosign and gitsign
FROM --platform=linux/amd64   quay.io/securesign/cli-cosign@sha256:83744c67787c8ed8ba24e1051ab7be9b1ca3ea36afaa0f7a2a8759b7639258e3 AS cosign-amd64
FROM --platform=linux/arm64   quay.io/securesign/cli-cosign@sha256:83744c67787c8ed8ba24e1051ab7be9b1ca3ea36afaa0f7a2a8759b7639258e3 AS cosign-arm64
FROM --platform=linux/ppc64le quay.io/securesign/cli-cosign@sha256:83744c67787c8ed8ba24e1051ab7be9b1ca3ea36afaa0f7a2a8759b7639258e3 AS cosign-ppc64le
FROM --platform=linux/s390x   quay.io/securesign/cli-cosign@sha256:83744c67787c8ed8ba24e1051ab7be9b1ca3ea36afaa0f7a2a8759b7639258e3 AS cosign-s390x

FROM --platform=linux/amd64   quay.io/securesign/gitsign@sha256:a4aae22ed64b25ea1124aed133e8751811e6b9be8a7c11ea7f06eca61e2579fc AS gitsign-amd64
FROM --platform=linux/arm64   quay.io/securesign/gitsign@sha256:a4aae22ed64b25ea1124aed133e8751811e6b9be8a7c11ea7f06eca61e2579fc AS gitsign-arm64
FROM --platform=linux/ppc64le quay.io/securesign/gitsign@sha256:a4aae22ed64b25ea1124aed133e8751811e6b9be8a7c11ea7f06eca61e2579fc AS gitsign-ppc64le
FROM --platform=linux/s390x   quay.io/securesign/gitsign@sha256:a4aae22ed64b25ea1124aed133e8751811e6b9be8a7c11ea7f06eca61e2579fc AS gitsign-s390x

# Provides the Trusted Artifact Signer CLI binary, fetch-tsa-certs
FROM --platform=linux/amd64 quay.io/securesign/fetch-tsa-certs@sha256:7f9161472efbee1efe7fb85d9f478bb9a7e204689b6ff584051ae78e04906e81 as fetch_tsa_certs-amd64
FROM --platform=linux/arm64 quay.io/securesign/fetch-tsa-certs@sha256:7f9161472efbee1efe7fb85d9f478bb9a7e204689b6ff584051ae78e04906e81 as fetch_tsa_certs-arm64
FROM --platform=linux/ppc64le quay.io/securesign/fetch-tsa-certs@sha256:7f9161472efbee1efe7fb85d9f478bb9a7e204689b6ff584051ae78e04906e81 as fetch_tsa_certs-ppc64le
FROM --platform=linux/s390x quay.io/securesign/fetch-tsa-certs@sha256:7f9161472efbee1efe7fb85d9f478bb9a7e204689b6ff584051ae78e04906e81 as fetch_tsa_certs-s390x

# Provides the Trusted Artifact Signer CLI binaries, rekor-cli and ec
FROM --platform=linux/amd64 quay.io/securesign/rekor-cli@sha256:26b4c828ed937ecb56c4bc768ad395102b3a864fe8f0f6d2aad1e0728c8c66cb as rekor-amd64
FROM --platform=linux/arm64 quay.io/securesign/rekor-cli@sha256:26b4c828ed937ecb56c4bc768ad395102b3a864fe8f0f6d2aad1e0728c8c66cb as rekor-arm64
FROM --platform=linux/ppc64le quay.io/securesign/rekor-cli@sha256:26b4c828ed937ecb56c4bc768ad395102b3a864fe8f0f6d2aad1e0728c8c66cb as rekor-ppc64le
FROM --platform=linux/s390x quay.io/securesign/rekor-cli@sha256:26b4c828ed937ecb56c4bc768ad395102b3a864fe8f0f6d2aad1e0728c8c66cb as rekor-s390x

FROM registry.redhat.io/rhtas/ec-rhel9:0.8-1776979197@sha256:52ff87e53a584265e5cdb67551e123185e3b3937cfecf2f0ac486894fc44c4d1 as ec

# Provides the Trusted Artifact Signer CLI binaries trillian-createtree and trillian-updatetree
FROM --platform=linux/amd64 quay.io/securesign/trillian-createtree@sha256:63097050f64bb94f990daa4226dbcabf427bdb853d8a3e9c79101ac90c6f3711 as trillian-createtree-amd64
FROM --platform=linux/arm64 quay.io/securesign/trillian-createtree@sha256:63097050f64bb94f990daa4226dbcabf427bdb853d8a3e9c79101ac90c6f3711 as trillian-createtree-arm64
FROM --platform=linux/ppc64le quay.io/securesign/trillian-createtree@sha256:63097050f64bb94f990daa4226dbcabf427bdb853d8a3e9c79101ac90c6f3711 as trillian-createtree-ppc64le
FROM --platform=linux/s390x quay.io/securesign/trillian-createtree@sha256:63097050f64bb94f990daa4226dbcabf427bdb853d8a3e9c79101ac90c6f3711 as trillian-createtree-s390x

FROM --platform=linux/amd64 quay.io/securesign/trillian-updatetree@sha256:4dcc7475f06622d7c73916b48613b6501b6e631aae2b574b20eb0dfa616444ce as trillian-updatetree-amd64
FROM --platform=linux/arm64 quay.io/securesign/trillian-updatetree@sha256:4dcc7475f06622d7c73916b48613b6501b6e631aae2b574b20eb0dfa616444ce as trillian-updatetree-arm64
FROM --platform=linux/ppc64le quay.io/securesign/trillian-updatetree@sha256:4dcc7475f06622d7c73916b48613b6501b6e631aae2b574b20eb0dfa616444ce as trillian-updatetree-ppc64le
FROM --platform=linux/s390x quay.io/securesign/trillian-updatetree@sha256:4dcc7475f06622d7c73916b48613b6501b6e631aae2b574b20eb0dfa616444ce as trillian-updatetree-s390x

FROM quay.io/securesign/cli-tuftool@sha256:0b5fce06b3367d251f68a26e528a6733e1e4329d4284e6a8ea2367a1cb3f2225 as tuf-tool

FROM registry.redhat.io/ubi9/httpd-24@sha256:e44ddd84a5d86c800f758ae0f09ebe321ec997d0e546c80db6ea8263c6a054d8
ENV APP_ROOT=/opt/app-root
WORKDIR $APP_ROOT/src/

RUN mkdir -p /var/www/html/clients/darwin && \
    mkdir -p /var/www/html/clients/linux && \
    mkdir -p /var/www/html/clients/windows

# Copy the cosign binaries from the previous stages
COPY --from=cosign-amd64 /usr/local/bin/cosign-darwin-amd64.gz /var/www/html/clients/darwin/cosign-amd64.gz
COPY --from=cosign-arm64 /usr/local/bin/cosign-darwin-arm64.gz /var/www/html/clients/darwin/cosign-arm64.gz
COPY --from=cosign-amd64 /usr/local/bin/cosign.gz /var/www/html/clients/linux/cosign-amd64.gz
COPY --from=cosign-arm64 /usr/local/bin/cosign.gz /var/www/html/clients/linux/cosign-arm64.gz
COPY --from=cosign-ppc64le /usr/local/bin/cosign.gz /var/www/html/clients/linux/cosign-ppc64le.gz
COPY --from=cosign-s390x /usr/local/bin/cosign.gz /var/www/html/clients/linux/cosign-s390x.gz
COPY --from=cosign-amd64 /usr/local/bin/cosign-windows-amd64.exe.gz /var/www/html/clients/windows/cosign-amd64.gz

# Copy the gitsign binaries from the previous stages
COPY --from=gitsign-amd64 /usr/local/bin/gitsign_cli_darwin_amd64.gz /var/www/html/clients/darwin/gitsign-amd64.gz
COPY --from=gitsign-arm64 /usr/local/bin/gitsign_cli_darwin_arm64.gz /var/www/html/clients/darwin/gitsign-arm64.gz
COPY --from=gitsign-amd64 /usr/local/bin/gitsign_cli_linux.gz /var/www/html/clients/linux/gitsign-amd64.gz
COPY --from=gitsign-arm64 /usr/local/bin/gitsign_cli_linux.gz /var/www/html/clients/linux/gitsign-arm64.gz
COPY --from=gitsign-ppc64le /usr/local/bin/gitsign_cli_linux.gz /var/www/html/clients/linux/gitsign-ppc64le.gz
COPY --from=gitsign-s390x /usr/local/bin/gitsign_cli_linux.gz /var/www/html/clients/linux/gitsign-s390x.gz
COPY --from=gitsign-amd64 /usr/local/bin/gitsign_cli_windows_amd64.exe.gz /var/www/html/clients/windows/gitsign-amd64.gz

# Copy the rekor binaries from the previous stages
COPY --from=rekor-amd64 /usr/local/bin/rekor_cli_darwin_amd64.gz /var/www/html/clients/darwin/rekor-cli-amd64.gz
COPY --from=rekor-arm64 /usr/local/bin/rekor_cli_darwin_arm64.gz /var/www/html/clients/darwin/rekor-cli-arm64.gz
COPY --from=rekor-amd64 /usr/local/bin/rekor_cli_linux.gz /var/www/html/clients/linux/rekor-cli-amd64.gz
COPY --from=rekor-arm64 /usr/local/bin/rekor_cli_linux.gz /var/www/html/clients/linux/rekor-cli-arm64.gz
COPY --from=rekor-ppc64le /usr/local/bin/rekor_cli_linux.gz /var/www/html/clients/linux/rekor-cli-ppc64le.gz
COPY --from=rekor-s390x /usr/local/bin/rekor_cli_linux.gz /var/www/html/clients/linux/rekor-cli-s390x.gz
COPY --from=rekor-amd64 /usr/local/bin/rekor_cli_windows_amd64.exe.gz /var/www/html/clients/windows/rekor-cli-amd64.gz

# Copy the ec binaries from the previous stages
COPY --from=ec /usr/local/bin/ec_darwin_amd64.gz      /var/www/html/clients/darwin/ec-amd64.gz
COPY --from=ec /usr/local/bin/ec_darwin_arm64.gz      /var/www/html/clients/darwin/ec-arm64.gz
COPY --from=ec /usr/local/bin/ec_linux_amd64.gz       /var/www/html/clients/linux/ec-amd64.gz
COPY --from=ec /usr/local/bin/ec_linux_arm64.gz       /var/www/html/clients/linux/ec-arm64.gz
COPY --from=ec /usr/local/bin/ec_linux_ppc64le.gz     /var/www/html/clients/linux/ec-ppc64le.gz
COPY --from=ec /usr/local/bin/ec_linux_s390x.gz       /var/www/html/clients/linux/ec-s390x.gz
COPY --from=ec /usr/local/bin/ec_windows_amd64.exe.gz /var/www/html/clients/windows/ec-amd64.gz

# Copy the fetch-tsa-certs binaries from the previous stages
COPY --from=fetch_tsa_certs-arm64 /usr/local/bin/fetch_tsa_certs_darwin_arm64.gz  /var/www/html/clients/darwin/fetch-tsa-certs-arm64.gz
COPY --from=fetch_tsa_certs-amd64 /usr/local/bin/fetch_tsa_certs_darwin_amd64.gz  /var/www/html/clients/darwin/fetch-tsa-certs-amd64.gz
COPY --from=fetch_tsa_certs-amd64 /usr/local/bin/fetch_tsa_certs_linux.gz  /var/www/html/clients/linux/fetch-tsa-certs-amd64.gz
COPY --from=fetch_tsa_certs-arm64 /usr/local/bin/fetch_tsa_certs_linux.gz  /var/www/html/clients/linux/fetch-tsa-certs-arm64.gz
COPY --from=fetch_tsa_certs-ppc64le /usr/local/bin/fetch_tsa_certs_linux.gz /var/www/html/clients/linux/fetch-tsa-certs-ppc64le.gz
COPY --from=fetch_tsa_certs-s390x /usr/local/bin/fetch_tsa_certs_linux.gz   /var/www/html/clients/linux/fetch-tsa-certs-s390x.gz
COPY --from=fetch_tsa_certs-amd64 /usr/local/bin/fetch_tsa_certs_windows_amd64.exe.gz /var/www/html/clients/windows/fetch-tsa-certs-amd64.gz

# Copy the trillian-createtree binaries from the previous stages
COPY --from=trillian-createtree-arm64 /usr/local/bin/createtree-darwin-arm64.gz /var/www/html/clients/darwin/createtree-arm64.gz
COPY --from=trillian-createtree-amd64 /usr/local/bin/createtree-darwin-amd64.gz /var/www/html/clients/darwin/createtree-amd64.gz
COPY --from=trillian-createtree-amd64 /usr/local/bin/createtree.gz /var/www/html/clients/linux/createtree-amd64.gz
COPY --from=trillian-createtree-arm64 /usr/local/bin/createtree.gz /var/www/html/clients/linux/createtree-arm64.gz
COPY --from=trillian-createtree-ppc64le /usr/local/bin/createtree.gz /var/www/html/clients/linux/createtree-ppc64le.gz
COPY --from=trillian-createtree-s390x /usr/local/bin/createtree.gz /var/www/html/clients/linux/createtree-s390x.gz
COPY --from=trillian-createtree-amd64 /usr/local/bin/createtree-windows-amd64.exe.gz /var/www/html/clients/windows/createtree-amd64.gz

# Copy the trillian-updatetree binaries from the previous stages
COPY --from=trillian-updatetree-arm64 /usr/local/bin/updatetree-darwin-arm64.gz /var/www/html/clients/darwin/updatetree-arm64.gz
COPY --from=trillian-updatetree-amd64 /usr/local/bin/updatetree-darwin-amd64.gz /var/www/html/clients/darwin/updatetree-amd64.gz
COPY --from=trillian-updatetree-amd64 /usr/local/bin/updatetree.gz /var/www/html/clients/linux/updatetree-amd64.gz
COPY --from=trillian-updatetree-arm64 /usr/local/bin/updatetree.gz /var/www/html/clients/linux/updatetree-arm64.gz
COPY --from=trillian-updatetree-ppc64le /usr/local/bin/updatetree.gz /var/www/html/clients/linux/updatetree-ppc64le.gz
COPY --from=trillian-updatetree-s390x /usr/local/bin/updatetree.gz /var/www/html/clients/linux/updatetree-s390x.gz
COPY --from=trillian-updatetree-amd64 /usr/local/bin/updatetree-windows-amd64.exe.gz /var/www/html/clients/windows/updatetree-amd64.gz

COPY --from=tuf-tool /usr/bin/tuftool /var/www/html/clients/linux/tuftool-amd64
RUN gzip /var/www/html/clients/linux/tuftool-amd64

COPY LICENSE /licenses/license.txt

LABEL \
      com.redhat.component="trusted-artifact-signer-serve-cli-container" \
      name="rhtas/client-server-rhel9" \
      version="1.3.0" \
      summary="Red Hat serves Trusted Artifact Signer CLI binaries cosign, gitsign, rekor-cli, ec, fetch_tsa_certs, trillian-createtree and trillian-updatetree from an HTTP server" \
      description="Serves Trusted Artifact Signer CLI binaries cosign, gitsign, rekor-cli, ec, fetch_tsa_certs, trillian-createtree and trillian-updatetree from an HTTP server" \
      io.k8s.description="Serves Trusted Artifact Signer CLI binaries cosign, gitsign, rekor-cli, ec, fetch_tsa_certs, trillian-createtree and trillian-updatetree from an HTTP server" \
      io.k8s.display-name="Red Hat serves Trusted Artifact Signer CLI binaries cosign, gitsign, rekor-cli, ec, fetch_tsa_certs, trillian-createtree and trillian-updatetree" \
      io.openshift.tags=" cosign, gitsign, rekor-cli, ec, fetch_tsa_certs, trillian-createtree and trillian-updatetree, rhtas, trusted, artifact, signer, sigstore" \
      maintainer="trusted-artifact-signer@redhat.com"
