# Build stage
FROM registry.redhat.io/ubi9/go-toolset:9.8-1790174511@sha256:0a4666f7a4eb0644c97a73cba198eb268691b270d97831822689e7a2088f87be AS build-env

WORKDIR /cosign
COPY . .
USER root
RUN git config --global --add safe.directory /cosign && \
    git update-index --assume-unchanged Dockerfile.cosign.rh && \
    go mod edit -godebug=fips140=auto && \
    go mod vendor && \
    make -f Build.mak cosign-linux && \
    git update-index --no-assume-unchanged Dockerfile.cosign.rh

# Install Cosign
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:8ebe2ad8fdf3cab3e5a53c1edc69194c98209cfadab24b884f4ad9ebcf7bbbfc

LABEL description="Cosign is a container signing tool that leverages simple, secure, and auditable signatures based on simple primitives and best practices."
LABEL io.k8s.description="Cosign is a container signing tool that leverages simple, secure, and auditable signatures based on simple primitives and best practices."
LABEL io.k8s.display-name="Cosign container image for Red Hat Trusted Signer"
LABEL io.openshift.tags="cosign trusted-signer"
LABEL summary="Provides the cosign CLI binary for signing and verifying container images."
LABEL com.redhat.component="cosign"
LABEL name="rhtas/cosign-rhel9"

COPY --from=build-env /cosign/cosign /usr/local/bin/cosign
COPY LICENSE /licenses/license.txt

RUN chown root:0 /usr/local/bin/cosign && chmod g+wx /usr/local/bin/cosign

# Configure home directory
ENV HOME=/home
RUN chgrp -R 0 /${HOME} && chmod -R g=u /${HOME}

WORKDIR ${HOME}

USER 65532:65532

# Makes sure the container stays running
CMD ["tail", "-f", "/dev/null"]
